### ISSUE TITLE
Change output folder

### ISSUE THREAD

**Issue by pmsound** [mkupferman/rfexplorer-detailed-scan#1]
Hello,
thank you so much for putting this together! As a complete newbie to python i managed to get RF Explorer Detailed Scan running on my macbook and can now use it out in the field during TV productions. Is it possible to change the output folder where the generated .csv file is stored in? 
Kindly regards,
peter

**Comment by mkupferman** [comment]
Hi Peter,

The OUTPUT_FILE argument is in fact a file path. So when you specify simply a filename ("scan.csv"), it will save to your current directory. You can also specify a relative path (e.g. "../myScans/scan1.csv" will go up a level and write scan1.csv inside a folder called "myScans") or an absolute path ("/home/myaccount/myScans/scan1.csv").

Those are examples for a UNIX-like operating system. If you are using Windows there are two ways to write paths:
1. In something like 'git bash', relative paths will be the same as UNIX ("directory1/directory2/scan.csv"), and your absolute paths might look like "/c/users/myAccount/desktop/scan.csv".
2. In a cmd.exe or powershell, use backslashes. A relative path: "..\myScans\scan1.csv". An absolute path (assuming you are on the 'C:' drive): "\users\myAccount\desktop\scan.csv"

**** EDIT ****
I just realized you said you are on a Mac. If you want to save them to a folder on your desktop called "myScans", you might write the output file like this: `~/Desktop/myScans/scan.csv`.

If you want to create an icon on your desktop that you can quickly double-click to save a new scan, you might want to create a file like this called, say "scan.command" (change the path to your python virtual environment and scan folder)

```
#!/bin/bash
APP=~/Desktop/rfexplorer-detailed-scan/venv/bin/rfexplorerDetailedScan
OPTS="-s 470 -e 600"
DEST=~/Desktop/myScans/$(date +%Y%m%d-%H%M%S).csv

$APP $OPTS $DEST
```
Be sure to make it executable (`chmod +x scan.command`), create the folder (`mkdir ~/Desktop/myScans`) and then you can double-click it to save a scan with the date/time in its name.

**Comment by pmsound** [comment]
Hello,
thank you very much for your reply!
That worked well, so this is going to be part of saturday’s German Bundesliga production. :)
Greetings from Frankfurt
Peter
