### ISSUE TITLE
Script does not work with RF Explorer Pro

### ISSUE THREAD

**Issue by Jaessr666** [mkupferman/rfexplorer-detailed-scan#3]
The script doesn't start a scan with rf explorer pro. (rack version)
The device restarts and is detected but as soon as it's supposed to scan it's stuck and doesn't do anything.
With the rf explorer handheld it works as it should

**Comment by mkupferman** [comment]
Unfortunately device support is a function of the https://github.com/RFExplorer/RFExplorer-for-Python package, which I do not maintain, nor do I have your RF Explorer model to test on. You might try asking the maintainers of that package, though!
